# Bagging

In [1]:
# importing Decision Tree for Classifiction 
import pandas as pd 
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

filename="/content/pima-indians-diabetes.data.csv"

names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)

array=dataframe.values
X=array[:,:8]
Y=array[:,8]
seed=7  

In [2]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [3]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [4]:
 # evaluation method(random_state=seed,shuffle=True)=denotes bootstrap method, # if no suffle it will adopt cross valiadation
kfold=KFold(n_splits=10,random_state=seed,shuffle=True)  
cart=DecisionTreeClassifier()
num_tree=100   # will create 100 decision tree 

model=BaggingClassifier(base_estimator=cart,n_estimators=num_tree,random_state=seed)  # classifier
results=cross_val_score(model,X,Y,cv=kfold)

print(results.mean())

0.7578263841421736


In [5]:
results

array([0.76623377, 0.75324675, 0.74025974, 0.77922078, 0.80519481,
       0.79220779, 0.66233766, 0.75324675, 0.78947368, 0.73684211])

# Random forest Classification

In [6]:
 from pandas import read_csv
 from numpy import array
 from sklearn.model_selection import KFold 
 from sklearn.model_selection import cross_val_score
 from sklearn.ensemble import RandomForestClassifier

filename ="/content/pima-indians-diabetes.data.csv"

names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)

array=dataframe.values
X=array[:,:8]
Y=array[:,8]


In [7]:
from pandas.core.reshape.merge import Suffixes
num_tree=100
max_features=3

kfold=KFold(n_splits=10,random_state=7,shuffle=True) # bootstrap

model=RandomForestClassifier(n_estimators=num_tree,max_features=max_features)
results=cross_val_score(model,X,Y,cv=kfold)
print(results.mean())

0.7669343814080656


# Boosting (AdaBoost)

In [8]:
 from pandas import read_csv
 from numpy import array
 from sklearn.model_selection import KFold 
 from sklearn.model_selection import cross_val_score
 from sklearn.ensemble import AdaBoostClassifier

filename ="/content/pima-indians-diabetes.data.csv"

names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)

array=dataframe.values
X=array[:,:8]
Y=array[:,8]


In [9]:
num_tree=10
seed=7

kfold=KFold(n_splits=10,random_state=seed,shuffle=True)
model=AdaBoostClassifier(n_estimators=num_tree,random_state=seed)
result=cross_val_score(model,X,Y,cv=kfold)
print(result.mean())

0.7669685577580314


# Stacking Ensemble for Classification

In [10]:
from pandas import read_csv
from numpy import array
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

filename ="/content/pima-indians-diabetes.data.csv"

names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)

array=dataframe.values
X=array[:,:8]
Y=array[:,8]


In [11]:
kfold=KFold(n_splits=10,random_state=7,shuffle=True)

#### Creating sub models

In [12]:
estimators=[]
model1=LogisticRegression(max_iter=500)
estimators.append(('logistic',model1))
model2=DecisionTreeClassifier()
estimators.append(('cart',model2))
model3=SVC()
estimators.append(('svm',model3))


##### Create the Ensemble model

In [13]:
from sklearn import ensemble
ensemble=VotingClassifier(estimators)
results=cross_val_score(ensemble,X,Y,cv=kfold)
print(results.mean())

0.7669685577580314


In [14]:
estimators

[('logistic', LogisticRegression(max_iter=500)),
 ('cart', DecisionTreeClassifier()),
 ('svm', SVC())]